name: macos

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - '.readthedocs.yaml'
    tags:
      - V**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source cmake
          brew install create-dmg

      - name: Build all
        run: |
          git fetch --tags --force
          sed -i'.original' -e 's/--long --dirty/--long/g' ./tools/generate_info.sh
          sed -i'.original' -e 's/QT_DIR=\/opt\/Qt6.2.0\/6.2.0\/gcc_64/QT_DIR=$(cd "$(dirname "$0")";pwd)\/..\/Qt\/6.5.3\/macos/g' build_dmg.sh
          sed -i'.original' -e 's/\/home\/qqm\/Desktop\/ttfviewer\/depend\/freetype/\/usr\/local\/ttfviewer/g' partform_unix.pri
          cd depend
          sudo ./build.sh
          cd -
          ./build_dmg.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TTFviewer_macos
          path: |
            ./dmgOut/*.dmg

      - name: Run tests
        run: |
          sudo hdiutil attach ./build_release/out/TTFviewer.dmg
          /Volumes/TTFviewer/TTFviewer.app/Contents/MacOS/TTFviewer --version

  macos_arm64:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source cmake
          brew install create-dmg

      - name: Build all
        run: |
          git fetch --tags --force
          sed -i'.original' -e 's/--long --dirty/--long/g' ./tools/generate_info.sh
          sed -i'.original' -e 's/QT_DIR=\/opt\/Qt6.2.0\/6.2.0\/gcc_64/QT_DIR=$(cd "$(dirname "$0")";pwd)\/..\/Qt\/6.5.3\/macos/g' build_dmg.sh
          sed -i'.original' -e 's/\/home\/qqm\/Desktop\/ttfviewer\/depend\/freetype/\/usr\/local\/ttfviewer/g' partform_unix.pri
          cd depend
          sudo ./build.sh
          cd -
          ./build_dmg.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TTFviewer_macos_arm64
          path: |
            ./dmgOut/*.dmg

      - name: Run tests
        run: |
          sudo hdiutil attach ./build_release/out/TTFviewer.dmg
          /Volumes/TTFviewer/TTFviewer.app/Contents/MacOS/TTFviewer --version
